### PR TITLE
#12

### PR DESCRIPTION
**Pull request by tzinadah**
Added utility method for hashing and used it on user passwords. Also my bad for making commits on main branch I just forgot to make a new one for the feature

### CODE REVIEW

**Review by Vikranth3140 — CHANGES_REQUESTED** [review]
Hey @tzinadah,

The updates look good to me! I have a few follow-up points to ensure everything is in line:

1. Could you please provide a quick demo video showing the password hashing in action? It would help us validate the recent changes visually.

2. Please ensure the code formatting is uniform across the codebase for better readability and maintainability.

Thanks for your work on this!

**Comment by tzinadah** [comment]
> Hey @tzinadah,
> 
> The updates look good to me! I have a few follow-up points to ensure everything is in line:
> 
>     1. Could you please provide a quick demo video showing the password hashing in action? It would help us validate the recent changes visually.
> 
>     2. Please ensure the code formatting is uniform across the codebase for better readability and maintainability.
> 
> 
> Thanks for your work on this!

would an image of the different stages of hashed password suffice as a demo?
what changes to formatting would you like?

**Comment by Vikranth3140** [comment]
> > Hey @tzinadah,
> > The updates look good to me! I have a few follow-up points to ensure everything is in line:
> > ```
> > 1. Could you please provide a quick demo video showing the password hashing in action? It would help us validate the recent changes visually.
> > 
> > 2. Please ensure the code formatting is uniform across the codebase for better readability and maintainability.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks for your work on this!
> 
> would an image of the different stages of hashed password suffice as a demo? what changes to formatting would you like?

Sure, images of registering and logging in of 1 User and 1 Admin should be good to go.

**Comment by Vikranth3140** [comment]
> > > > Hey @tzinadah,
> > > > The updates look good to me! I have a few follow-up points to ensure everything is in line:
> > > > ```
> > > > 1. Could you please provide a quick demo video showing the password hashing in action? It would help us validate the recent changes visually.
> > > > 
> > > > 2. Please ensure the code formatting is uniform across the codebase for better readability and maintainability.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Thanks for your work on this!
> > > 
> > > 
> > > would an image of the different stages of hashed password suffice as a demo? what changes to formatting would you like?
> > 
> > 
> > Sure, images of registering and logging in of 1 User and 1 Admin should be good to go.
> 
> Demo Hash_Demo
> 
> I also added a commit to change with formatted code

Lgtm, please checkout the 3 other reviews which i have requested and clear it to me.

**Comment by tzinadah** [comment]
> > > > > Hey @tzinadah,
> > > > > The updates look good to me! I have a few follow-up points to ensure everything is in line:
> > > > > ```
> > > > > 1. Could you please provide a quick demo video showing the password hashing in action? It would help us validate the recent changes visually.
> > > > > 
> > > > > 2. Please ensure the code formatting is uniform across the codebase for better readability and maintainability.
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Thanks for your work on this!
> > > > 
> > > > 
> > > > would an image of the different stages of hashed password suffice as a demo? what changes to formatting would you like?
> > > 
> > > 
> > > Sure, images of registering and logging in of 1 User and 1 Admin should be good to go.
> > 
> > 
> > Demo Hash_Demo
> > I also added a commit to change with formatted code
> 
> Lgtm, please checkout the 3 other reviews which i have requested and clear it to me.

I think I made the two changes you requessted. I don't know what exactly do you mean by the 3 reviews

**Comment by Vikranth3140** [comment]
Hi @tzinadah, please see all the reviewed changes i have requested, you can find them above the comments and chats in this PR discussion.

I have left 7 reviewed changes on which I need clarity.

**Comment by Vikranth3140** [comment]
To simplify it, I would suggest you to only add the functionally without changing the code consistency, formatting and structure of the codebase, and add your functions adhering to the other pieces of code.

Please have a look at the reviews and you will have some clarity on this.

**Comment by tzinadah** [comment]
> pdates look good to me! I

The requested changes points me to this review which I believe I addressed. And I made a commit to format my functions to follow the codebase formatting so can I get a more specefic desired design for the codebase?

**Comment by tzinadah** [comment]
Does this last commit solve the issue?

**Comment by Vikranth3140** [comment]
Please clear all the reviewed changes

**Review by tzinadah — COMMENTED** [review]
I commented on all portions of the new code

**Comment by Vikranth3140** [comment]
Hey @tzinadah,

I also do not see why you would make any changes in `Main.java` as I believe there is no need to handle anything in that class.

Let's do 1 thing,

Please store your changes in the code locally and delete the forked repository, and fork the repo again and only make your relevant changes in `Hash.java` and `User.java` and send another PR and link it back to this PR.

I will review the changes myself and finalize it to not make it more complicated.


Additionally, while submitting the PR, do verify the hashing passwords for `User` and `Admin`.

Thanks for your work on this!

**Comment by tzinadah** [comment]
I will close this PR and open another one that takes the new changes in mind

**Pull request closed without merging**
