### PR TITLE
Feature/password hashing #12

### PR DESCRIPTION
**Pull request by tzinadah**
# Hash Demo
Hash_Demo

### CODE REVIEW

**Comment by Vikranth3140** [comment]
This PR intends to close #12.

Please confirm that you have verified the working of the password hashing of `User` and `Admin`.

**Review by Vikranth3140 — APPROVED** [review]
Lgtm

**Comment by Vikranth3140** [comment]
Cool, Before i merge, please update the README as well with the changes you have implemented.

**Comment by tzinadah** [comment]
Readme updated

**Comment by Vikranth3140** [comment]
also please include it in the `Project Structure` of the `README.md`.

After that everything's good to go.

**Comment by Vikranth3140** [comment]
Hey @tzinadah,

Congratulations on the merged PR.
Thanks a lot for your contribution to #12.

Checkout other repositories to contribute at [Repos](https://github.com/Vikranth3140?tab=repositories).

**Pull request merged**
